### ISSUE TITLE
Cannot build the env image for django

### ISSUE THREAD

**Issue by zyone1991** [logic-star-ai/swt-bench#4]
### Describe the bug

When building the env image for django, the error below occurred:

> Running 299 unevaluated instances...
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/swtbench/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/anaconda3/envs/swtbench/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/local/home/user/swt-bench/src/main.py", line 126, in <module>
    run(**vars(args))
  File "/local/home/user/swt-bench/src/main.py", line 74, in run
    run_instances(predicted_tests, dataset, compute_coverage, cache_level, clean, force_rebuild, max_workers, run_id, patch_types, timeout, client, build_mode)
  File "/local/home/user/swt-bench/src/run_evaluation.py", line 300, in run_instances
    instance_image_ids = {x.exec_spec.instance_image_key for x in test_specs}
  File "/local/home/user/swt-bench/src/run_evaluation.py", line 300, in <setcomp>
    instance_image_ids = {x.exec_spec.instance_image_key for x in test_specs}
  File "/local/home/user/swt-bench/src/exec_spec.py", line 140, in instance_image_key
    return f"exec.eval.{self.arch}.{self.env_hash}.{self.instance_hash}:latest"
  File "/local/home/user/swt-bench/src/exec_spec.py", line 145, in env_hash
    hash_object.update(self.env_script.encode("utf-8"))
  File "/local/home/user/swt-bench/src/exec_spec.py", line 106, in env_script
    return "\n".join(["#!/bin/bash", "set -euxo pipefail"] + self.env_script_list) + "\n"
  File "/local/home/user/swt-bench/src/exec_spec.py", line 334, in env_script_list
    reqs_commands += self.req_install_commands
  File "/local/home/user/swt-bench/src/exec_spec.py", line 282, in req_install_commands
    reqs = get_requirements_by_commit(self.repo, self.environment_setup_commit)
  File "/local/home/user/swt-bench/src/utils.py", line 159, in get_requirements_by_commit
    raise ValueError(
ValueError: Could not find requirements.txt at paths ['tests/requirements/py3.txt'] for repo django/django at commit 419a78300f7cd27611196e1e464d50fd0385ff27
 

I believe this is related to the issue of swebench here (https://github.com/princeton-nlp/SWE-bench/issues/248), for which you need to add headers to the request. 

### Steps/Code to Reproduce

python -m src.main \
    --predictions_path gold \
    --max_workers 1 \
    --run_id validate-gold

### Expected Results

the image can be built

### Actual Results

the image fails to build

**Comment by zyone1991** [comment]
I created a PR #5 for this.

**Comment by nielstron** [comment]
Thank you for your PR. I have merged the changes!
